### ISSUE TITLE
Support for `@import`

### ISSUE THREAD

**Issue by oscarotero** [littledivy/deno_sass2#1]
Hi. I have been playing with this library, hoping to finally have a way to run SASS in Deno, but got an error importing files. For example, with this code:

```scss
@import "./sass/colors.scss";

html {
  color: $color;

  h1 {
    background-color: $color;
    color: $color2;
  }
}
```

I get a `RuntimeError`:

```
RuntimeError: unreachable
  at rust_panic (wasm://wasm/0041e5a6:1:857292)
  at std::panicking::rust_panic_with_hook::h01ce218e2160fe6f (wasm://wasm/0041e5a6:1:795639)
```

I guess this is a experimental repository, but is there any way add support for this?
Thanks!
